[build]
builder = "railpack"
buildCommand = "npm cache clean --force && npm install && npm run build"

[build.env]
NODE_ENV = "production"
SKIP_ENV_VALIDATION = "1"
NODE_VERSION = "22"
PYTHON = "/usr/bin/python3"
CC = "/usr/bin/gcc"
CXX = "/usr/bin/g++"

[deploy]
startCommand = "npm start"